# Generated by Django 4.1.5 on 2023-01-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "run_id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("run_date", models.DateField()),
                ("mlr_dataset", models.CharField(max_length=255)),
                ("feature_set", models.CharField(max_length=255)),
                ("split", models.FloatField()),
                ("tuned", models.BooleanField()),
                ("setup", models.CharField(max_length=1000)),
                ("best", models.CharField(max_length=1000)),
                ("holdout_acc", models.FloatField()),
                ("metrics_dict", models.CharField(max_length=1000)),
                ("accuracy", models.FloatField()),
                ("roc_auc", models.FloatField()),
                ("recall", models.FloatField()),
                ("precision", models.FloatField()),
                ("f1", models.FloatField()),
                ("kappa", models.FloatField()),
                ("mcc", models.FloatField()),
            ],
        ),
    ]
